### ISSUE TITLE
malicious franchisee can lock funds for full duration of trust

### ISSUE THREAD

**Issue by NickErrant** [skilesare/catallaxtrust#1]
After start of trust, current franchisee can set franchisee to address of a contract with fallback function that always throws, preventing withdraw from functioning. Assuming custodian does not stop uploading conversion rates (which is likely as they are designed to provide conversion rates for more than one trust), the funds will be locked for the full duration of the trust.

**Comment by skilesare** [comment]
Awesome catch.  The suggestion is to always use a withdraw pattern.  Any idea of a way to catch that kind of throw in solidity and continue unmolested?

**Comment by NickErrant** [comment]
The most secure way would be separating withdraw into separate functions for each of the relevant parties so that they can only make their own transaction fail (as you said, always use the withdraw pattern). However, I understand how that could be suboptimal for UX purposes.

A possible workaround is changing the franchisee's--and only the franchisee's--transfer() to send(). When send() fails an exception won't be propagated, instead it returns false. This would close up the locking issue, but potentially leave a franchisee without malicious intent out of a payment if their transfer fails for whatever reason.

Perhaps the two approaches could be combined: keep track of whether franchisee's send was successful, and if it was not, allow the franchisee to withdraw the missed payment through their own withdraw function.
